# Generated by Django 3.2.9 on 2021-11-25 03:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 3, 35, 40, 580758, tzinfo=utc)),
        ),
    ]
