# Generated by Django 3.2.9 on 2021-12-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregister',
            name='activated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
